@extends('layouts.user.layout')
@section('header')
    @include('layouts.user.header')
@endsection
@section('content')
    @include('shop.user.section.contact')
@endsection
@section('footer')
    @include('layouts.user.footer')
@endsection
