@extends('layouts.user.layout')
@section('header')
    @include('layouts.user.header')
@endsection
@section('content')
    @include('shop.user.section.product-single')
@endsection
@section('footer')
    @include('layouts.user.footer')
@endsection
